name: test_prj
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.14.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libcxx=19.1.7
  - libcxxabi=19.1.7
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python_abi=3.10
  - pyzmq=26.2.1
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - hydra-core==1.3.2
      - idna==3.10
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - pillow==11.1.0
      - pip==25.0.1
      - propcache==0.2.1
      - protobuf==5.29.3
      - pyparsing==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - sympy==1.13.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torch==2.2.2
      - torchmetrics==1.6.1
      - torchvision==0.17.2
      - tqdm==4.67.1
      - triton==2.2.0
      - yarl==1.18.3
