defaults:
  - _self_
  - optim: adam                                                                 
  - lr_scheduler: cosine_annealing                                               

batch_size: 32
max_epochs: 20

threshold: 0.5

# logger
save_top_k: 5

# accumulate_steps
nominal_batch_size: 32

# trainer params
precision: bf16-mixed
log_every_n_steps: 1
n_devices: 1
strategy: auto